### PR TITLE
Improve reports

### PR DESCRIPTION
**Pull request by jernst**
This probably a bit buggier than I would want, but I think we should still use this as the baseline as it produces better reports with clear-text descriptions of the tests.

There is also a new sequential HTML template that emits everything that happened in the sequence that it happened: makes failing tests easier to debug in case the test did not have as much isolation as one might have thought.

### CODE REVIEW

**Comment by steve-bate** [comment]
Something doesn't look right about this. The background color, for example. However, the app names are not being shown either so I'm not sure what's happening. The app names are in the test plan and in the JSON test transcript. To generate the following report in the screenshot, I merged your branch into my local workspace and generated the report.

**Comment by jernst** [comment]
Looks different from what I have. (Uploaded as .txt because Github doesn't like HTML)

[webfinger-results-all.html.txt](https://github.com/fediverse-devnet/feditest/files/15409596/webfinger-results-all.html.txt)

**Comment by jernst** [comment]
Related: https://github.com/fediverse-devnet/feditest-tests-fediverse/issues/86

**Comment by steve-bate** [comment]
> Looks different from what I have. (Uploaded as .txt because Github doesn't like HTML)
> 
> [webfinger-results-all.html.txt](https://github.com/fediverse-devnet/feditest/files/15409596/webfinger-results-all.html.txt)

I see the same thing with that file. According to the browser dev tools, it's caused by the following embedded styling.

```css

body {
    padding: 2rem;
    background: #f8f8f8;
}
```

The background is very close to being white.

**Comment by jernst** [comment]
I'm closing this. It got subsumed in the next PR.

**Pull request closed without merging**
