### PR TITLE
Update nodedriver decorator

### PR DESCRIPTION
**Pull request by steve-bate**
1. Add return type annotation (helps with IDE)
2. Return the annotated type (so import works)

### CODE REVIEW

**Comment by jernst** [comment]
Guess I have something to learn here: how does this help in (which?) IDE?

**Comment by steve-bate** [comment]
> Guess I have something to learn here: how does this help in (which?) IDE?

It helps by providing the correct type hint for the decorator return value (so autocompletion, etc., works effectively with the decorated class). I was using VS Code, but I suspect it would be similar for other IDEs like PyCharm.

**Comment by jernst** [comment]
I hadn't noticed that in VS Code, but then ...

**Comment by steve-bate** [comment]
> I hadn't noticed that in VS Code, but then ...

I was encountering it because I was unit testing a node driver. In the normal case where node drivers are only accessed through the global collection of registered drivers, the type hit wouldn't be very useful since the global collection has a mix of NodeDriver subtypes.

In VS Code you can hover over a variable (or function?) and it will tell you the declared or inferred type. Prior to the change, a node driver type was always `Any`. Now it's the type of the node driver class.

**Pull request merged**
