### PR TITLE
Support testing direct messages (via @mention) in Mastodon

### PR DESCRIPTION
**Pull request by jernst**
(this PR is smaller than it looks like -- my local branches got a bit messy)

### CODE REVIEW

**Comment by steve-bate** [comment]
Is it possible to git rebase the branch on `develop`?

**Comment by jernst** [comment]
I'll probably mess it up, but I'll try tomorrow.

**Review by steve-bate — APPROVED** [review]
Am I understanding correctly that the primary purpose of this PR to check both the home timeline and notifications for a posted status? I'm curious about under which conditions the note is only in notifications and not in the home timeline (I'm aware of the inverse) for a direct recipient.

**Comment by jernst** [comment]
Actually I do Squash and Merge, that should make the commit history less messy.

**Pull request merged**
